name: "Rubocop autofix"

on:
  schedule:
    - cron: '30 15 * * 5'

jobs:
  rubocop:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # If running on a self-hosted runner, check it meets the requirements
    # listed at https://github.com/ruby/setup-ruby#using-self-hosted-runners
    - name: Set up Ruby
      uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
      with:
        ruby-version: 3.1.3

    - name: Install dependencies
      run: bundle install

    - name: Rubocop run
      run: bundle exec rubocop -a

    - name: Create pull request
      uses: peter-evans/create-pull-request@v6.0.5
      with:
        commit-message: rubocop -a via ci-cd
        title: rubocop -a
        branch: fix/rubocop_autofix
